services:
  proxy-perforaciones:
    image: nginx:alpine
    container_name: proxy-perforaciones
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server-perforaciones:
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: server-perforaciones
    ports:
      - '3040:3040'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo-perforaciones
    depends_on:
      - mongo-perforaciones
  mongo-perforaciones:
    image: mongo
    container_name: mongo-perforaciones
    volumes:
      - data:/data/dbPerforaciones
    ports:
      - '27032:27017'
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=perforaciones
      - MONGO_INITDB_ROOT_PASSWORD=Perforaciones2025

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
